# -*- mode: ruby -*-
# vi: set ft=ruby :

# Use this Vagrant configuration file for local installation of the Oro application.
# Please, refer to the Oro Applications installation guides for the detailed instructions:
# https://doc.oroinc.com/backend/setup/dev-environment/vagrant/

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/oracle8"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  config.vm.network "forwarded_port", guest: 80, host: 8000

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/home/vagrant/www"
  config.vm.synced_folder "./", "/vagrant"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  #
   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true

     # Customize the amount of memory on the VM:
     vb.memory = 4096
     vb.cpus = 2
   end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL

    echo "\n*****************************************************"
    echo "************* Provision process started *************"
    echo "*****************************************************\n"

    # --------------------- Provision configuration ---------------------

    # --- VM settings ---

    FORWARDED_PORT=8000
    ORO_PHP_MODULE_VERSION=8.1
    ORO_NODEJS_MODULE_VERSION=16

    # --- Database settings ---

    DB_USER="dbuser"
    DB_PASSWORD="DBP@ssword123"
    DB_NAME="oro"

    echo "$DB_USER" > /tmp/oro_install_DB_USER
    echo "$DB_PASSWORD" > /tmp/oro_install_DB_PASSWORD
    echo "$DB_NAME" > /tmp/oro_install_DB_NAME

    # --- RabbitMQ settings ---

    RABBITMQ_USER="rbmquser"
    RABBITMQ_PASSWORD="rbmqpassword"

    echo "$RABBITMQ_USER" > /tmp/oro_install_RABBITMQ_USER
    echo "$RABBITMQ_PASSWORD" > /tmp/oro_install_RABBITMQ_PASSWORD

    # --- Oro application settings ---

    APP_HOST="localhost"
    APP_USER="admin"
    APP_PASSWORD="adminpass"
    APP_LOAD_DEMO_DATA="y"		# y | n

    echo "$APP_HOST" > /tmp/oro_install_APP_HOST
    echo "$APP_USER" > /tmp/oro_install_APP_USER
    echo "$APP_PASSWORD" > /tmp/oro_install_APP_PASSWORD
    echo "$APP_LOAD_DEMO_DATA" > /tmp/oro_install_APP_LOAD_DEMO_DATA

    LICENCE_KEY=#{ENV['licence']}
    GITHUB_TOKEN=#{ENV['gittoken']}

    if [ -z "$LICENCE_KEY" -o -z "$GITHUB_TOKEN" ]; then
      echo "\n\n\n!!!!!!! Warninig! You must provide your Enterprise Licence Key and your GitHub Token to be able to install Oro Enterprise Edition application before 'vagrant up' command (licence=YourEnterpsiseLicenceKey gittoken=yourgithubtoken vagrant up --provision) !!!!!!!\n\n\n"
      exit
    fi

    echo "$GITHUB_TOKEN" > /tmp/oro_install_GITHUB_TOKEN

    echo "\n*******************************************************"
    echo "************** Step 1: Environment Setup **************"
    echo "*******************************************************\n"

    dnf -y install dnf-plugin-config-manager https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    dnf -y module enable postgresql:13 redis:remi-6.2 nodejs:${ORO_NODEJS_MODULE_VERSION} php:remi-${ORO_PHP_MODULE_VERSION}
    dnf -y upgrade

    echo "\n~~~~~~~~~~~~~~ Enable Required Package Repositories ~~~~~~~~~~~~~~\n"

    if [[ ! -e /etc/yum.repos.d/oropublic.repo ]]; then
	    TMP_FILE=$(mktemp)
	    cat >"$TMP_FILE" <<__EOF__
[oropublic]
name=OroPublic
baseurl=https://nexus.oro.cloud/repository/oropublic/8/x86_64/
enabled=1
gpgcheck=0
module_hotfixes=1
__EOF__
    	mv -f "$TMP_FILE" "/etc/yum.repos.d/oropublic.repo"
    fi

    if [[ ! -e /etc/yum.repos.d/elasticsearch.repo ]]; then
	    TMP_FILE=$(mktemp)
	    cat >"$TMP_FILE" <<__EOF__
[elasticsearch]
name=Elasticsearch repository for 7.x packages
baseurl=https://artifacts.elastic.co/packages/7.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
__EOF__
      mv -f "$TMP_FILE" "/etc/yum.repos.d/elasticsearch.repo"
    fi
    rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

    curl -1sLf 'https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/setup.rpm.sh' | bash
    ## primary RabbitMQ signing key
    rpm --import https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    ## RabbitMQ server repository
    rpm --import https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey

    if [[ ! -e /etc/yum.repos.d/rabbitmq.repo ]]; then
	    TMP_FILE=$(mktemp)
	    cat >"$TMP_FILE" <<__EOF__
[rabbitmq_server]
name=rabbitmq_server
baseurl=https://packagecloud.io/rabbitmq/rabbitmq-server/el/8/x86_64/
repo_gpgcheck=1
gpgcheck=1
enabled=1
# PackageCloud's repository key and RabbitMQ package signing key
gpgkey=https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
       https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
__EOF__
      mv -f "$TMP_FILE" "/etc/yum.repos.d/rabbitmq.repo"
    fi

    echo "\n~~~~~~~~~~~~~~ Install Nginx, Install PHP, NodeJS, Wget ~~~~~~~~~~~~~~\n"
    dnf -y --setopt=install_weak_deps=False --best install pngquant jpegoptim findutils rsync glibc-langpack-en psmisc wget bzip2 unzip p7zip p7zip-plugins parallel \
    patch nodejs npm git-core jq bc postgresql postgresql-server postgresql-contrib redis elasticsearch rabbitmq-server \
    php-common php-cli php-fpm php-opcache php-mbstring php-mysqlnd php-pgsql php-pdo php-json php-process php-ldap php-gd php-intl php-bcmath php-xml php-soap php-sodium php-tidy php-imap php-pecl-zip php-pecl-mongodb
    dnf -y --setopt=install_weak_deps=False --best --nogpgcheck install oro-nginx oro-nginx-mod-http-cache_purge oro-nginx-mod-http-cookie_flag oro-nginx-mod-http-geoip oro-nginx-mod-http-gridfs oro-nginx-mod-http-headers_more oro-nginx-mod-http-naxsi oro-nginx-mod-http-njs oro-nginx-mod-http-pagespeed oro-nginx-mod-http-sorted_querystring oro-nginx-mod-http-testcookie_access oro-nginx-mod-http-xslt-filter

    echo "\n~~~~~~~~~~~~~~ Install Composer ~~~~~~~~~~~~~~\n"
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && php composer-setup.php
    php -r "unlink('composer-setup.php');"
    mv composer.phar /usr/bin/composer

    echo "********************************************************************************"
    echo "************** Step 2: Pre-installation Environment Configuration **************"
    echo "********************************************************************************"

    echo "\n~~~~~~~~~~~~~~ Perform Security Configuration ~~~~~~~~~~~~~~\n"

    sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config
    setenforce permissive
    systemctl disable --now firewalld

    echo "\n~~~~~~~~~~~~~~ Prepare PostgreSQL Database ~~~~~~~~~~~~~~\n"

    # --- Initialize a PostgreSQL Database Cluster ---

    postgresql-setup --initdb

    # --- Enable Password Protected PostgreSQL Authentication ---

    sed -i 's/all[ ]*127.0.0.1\\/32[ ]*ident/all   127.0.0.1\\/32   md5/g' /var/lib/pgsql/data/pg_hba.conf
    sed -i 's/all[ ]*::1\\/128[ ]*ident/all   ::1\\/128   md5/g' /var/lib/pgsql/data/pg_hba.conf

    # --- Change the Password for the postgres User ---

    systemctl start postgresql
    su - postgres -c "psql -U postgres -d postgres -c \\"alter user postgres with password '$DB_PASSWORD';\\""

    # --- Create a Database for OroCRM Enterprise Edition Application ---

    su - postgres -c "psql -U postgres -d postgres -c \\"CREATE DATABASE oro;\\""
    su - postgres -c "psql -U postgres -d oro -c 'CREATE EXTENSION IF NOT EXISTS \\"uuid-ossp\\";'"

    echo "\n~~~~~~~~~~~~~~ Configure Web Server ~~~~~~~~~~~~~~\n"

    cat > /etc/nginx/conf.d/default.conf <<____NGINXCONFIGTEMPLATE
server {
  server_name $APP_HOST www.$APP_HOST;
  root  /var/www/oroapp/public;

  index index.php;

  gzip on;
  gzip_proxied any;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
  gzip_vary on;

  location / {
    # try to serve file directly, fallback to index.php
    try_files \\$uri /index.php\\$is_args\\$args;
  }

  location ~ ^/(index|index_dev|config|install)\\.php(/|$) {
    fastcgi_pass php-fpm;
    fastcgi_split_path_info ^(.+\\.php)(/.*)$;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME \\$document_root\\$fastcgi_script_name;
    fastcgi_param HTTPS off;
    fastcgi_buffers 64 64k;
    fastcgi_buffer_size 128k;
  }

  location ~* ^[^(\\.php)]+\\.(jpg|jpeg|gif|png|ico|css|pdf|ppt|txt|bmp|rtf|js)$ {
    access_log off;
    expires 1h;
    add_header Cache-Control public;
  }

  error_log /var/log/nginx/${APP_HOST}_error.log;
  access_log /var/log/nginx/${APP_HOST}_access.log;
}
____NGINXCONFIGTEMPLATE

    echo "\n~~~~~~~~~~~~~~ Configure PHP ~~~~~~~~~~~~~~\n"

    sed -i 's/user = apache/user = nginx/g' /etc/php-fpm.d/www.conf
    sed -i 's/group = apache/group = nginx/g' /etc/php-fpm.d/www.conf
    sed -i 's/;catch_workers_output/catch_workers_output/g' /etc/php-fpm.d/www.conf

    sed -i 's/memory_limit = [0-9MG]*/memory_limit = 1G/g' /etc/php.ini
    sed -i 's/;realpath_cache_size = [0-9MGk]*/realpath_cache_size = 4M/g' /etc/php.ini
    sed -i 's/;realpath_cache_ttl = [0-9]*/realpath_cache_ttl = 600/g' /etc/php.ini

    sed -i 's/opcache.enable=[0-1]/opcache.enable=1/g' /etc/php.d/10-opcache.ini
    sed -i 's/;opcache.enable_cli=[0-1]/opcache.enable_cli=0/g' /etc/php.d/10-opcache.ini
    sed -i 's/opcache.memory_consumption=[0-9]*/opcache.memory_consumption=512/g' /etc/php.d/10-opcache.ini
    sed -i 's/opcache.interned_strings_buffer=[0-9]*/opcache.interned_strings_buffer=32/g' /etc/php.d/10-opcache.ini
    sed -i 's/opcache.max_accelerated_files=[0-9]*/opcache.max_accelerated_files=32531/g' /etc/php.d/10-opcache.ini
    sed -i 's/;opcache.save_comments=[0-1]/opcache.save_comments=1/g' /etc/php.d/10-opcache.ini

    echo "\n~~~~~~~~~~~~~~ Configure ElasticSearch ~~~~~~~~~~~~~~\n"

    echo '-Xms1g' >> /etc/elasticsearch/jvm.options
    echo '-Xmx1g' >> /etc/elasticsearch/jvm.options
    echo 'path.repo: /tmp' >> /etc/elasticsearch/elasticsearch.yml
    echo 'ingest.geoip.downloader.enabled: false' >> /etc/elasticsearch/elasticsearch.yml

    echo "\n~~~~~~~~~~~~~~ Configure RabbitMQ ~~~~~~~~~~~~~~\n"
    # --- Enable RabbitMQ Plugins ---
    pushd /usr/lib/rabbitmq/lib/rabbitmq_server-*/plugins/
    wget -q https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.9.0/rabbitmq_delayed_message_exchange-3.9.0.ez
    popd
    rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange
    rabbitmq-plugins enable --offline rabbitmq_management
    echo "127.0.0.1 $(hostname -s)" >> /etc/hosts
    systemctl start rabbitmq-server

    # --- Create RabbitMQ User ---
    rabbitmqctl add_user "$RABBITMQ_USER" "$RABBITMQ_PASSWORD"
    rabbitmqctl add_vhost "/oro"
    rabbitmqctl set_permissions -p "/oro" "$RABBITMQ_USER" ".*" ".*" ".*"

    while :; do
      rabbitmqctl authenticate_user "$RABBITMQ_USER" "$RABBITMQ_PASSWORD" >/dev/null 2>&1 && {
        echo
        rabbitmq-diagnostics status
      } && break
      echo -n "."
      sleep 1
      let w_timeout+=1
      [[ "$w_timeout" -lt 60 ]] || { echo "Can't run RMQ"; exit 1; }
    done
    sleep 1

    echo "\n~~~~~~~~~~~~~~ Enable Installed Services ~~~~~~~~~~~~~~\n"

    systemctl enable postgresql rabbitmq-server redis elasticsearch php-fpm nginx
    systemctl restart redis elasticsearch php-fpm nginx
    curl -I -XGET -k http://localhost:9200/_cluster/health

    echo "********************************************************************************************"
    echo "************************** Step 3: Oro Application Installation ****************************"
    echo "********************************************************************************************"
    echo "\n~~~~~~~~~~~~~~ Get Application Source Code ~~~~~~~~~~~~~~\n"

    # --- Copy application source code from the current host folder to the nginx web folder ---

    mkdir -p /var/www/oroapp
    cd /var/www/oroapp
    cp -r /vagrant/* .
    chown -R vagrant:vagrant .

    echo "\n~~~~~~~~~~~~~~ Install Application Dependencies ~~~~~~~~~~~~~~\n"

    # --- Install Dependencies ---

    mkdir -p ~/.ssh
    ssh-keyscan -t rsa -H github.com >> ~/.ssh/known_hosts
    su - vagrant -c 'GITHUB_TOKEN=$(cat /tmp/oro_install_GITHUB_TOKEN) && composer config -g github-oauth.github.com $GITHUB_TOKEN'
    su - vagrant -c 'composer install --no-progress --prefer-dist --no-dev --optimize-autoloader -n --working-dir=/var/www/oroapp'

    # --- Configure config/parameters.yml (to prevent composer interactive dialog) ---

    sed -i "s/database_driver:[ ]*pdo_mysql/database_driver: pdo_pgsql/g" ./config/parameters.yml
    sed -i "/database_name/s/:[[:space:]].*$/: $DB_NAME/g" ./config/parameters.yml
    sed -i "/database_user/s/:[[:space:]].*$/: postgres/g" ./config/parameters.yml
    sed -i "/database_password/s/:[[:space:]].*$/: '$DB_PASSWORD'/g" ./config/parameters.yml

    sed -i "/search_engine_name/s/:[[:space:]].*$/: elastic_search/g" ./config/parameters.yml

    sed -i "/session_handler/s/:[[:space:]].*$/: 'snc_redis.session.handler'\\n    redis_dsn_session: 'redis:\\/\\/127.0.0.1:6379\\/0'\\n    redis_dsn_cache: 'redis:\\/\\/127.0.0.1:6379\\/1'\\n    redis_dsn_doctrine: 'redis:\\/\\/127.0.0.1:6379\\/2'\\n    redis_setup: 'standalone'/g" ./config/parameters.yml

    sed -i "/enterprise_licence/s/:[[:space:]].*$/: '$LICENCE_KEY'/g" ./config/parameters.yml

    sed -i "/message_queue_transport/s/:[[:space:]].*$/: amqp/g" ./config/parameters.yml
    sed -i "/message_queue_transport_config/s/:[[:space:]].*$/: { host: '127.0.0.1', port: '5672', user: '$RABBITMQ_USER', password: '$RABBITMQ_PASSWORD', vhost: '\\/oro' }/g" ./config/parameters.yml
    chown vagrant:vagrant /var/www/oroapp/config/parameters.yml

    echo "\n~~~~~~~~~~~~~~ Install Oro Application ~~~~~~~~~~~~~~\n"

    su - vagrant -c 'APP_HOST=$(cat /tmp/oro_install_APP_HOST) && APP_USER=$(cat /tmp/oro_install_APP_USER) && APP_PASSWORD=$(cat /tmp/oro_install_APP_PASSWORD) && APP_LOAD_DEMO_DATA=$(cat /tmp/oro_install_APP_LOAD_DEMO_DATA) && php /var/www/oroapp/bin/console oro:install --env=prod --timeout=1500 --no-debug --application-url="http://$APP_HOST/" --organization-name="Oro Inc" --user-name="$APP_USER" --user-email="admin@example.com" --user-firstname="Bob" --user-lastname="Dylan" --user-password="$APP_PASSWORD" --sample-data=$APP_LOAD_DEMO_DATA --language=en --formatting-code=en_US'

    echo "\n~~~~~~~~~~~~~~ Add Required Permissions for the nginx User ~~~~~~~~~~~~~~\n"

    setfacl -b -R ./
    cd /var/www/oroapp
    find . -type f -exec chmod 0644 {} \\;
    find . -type d -exec chmod 0755 {} \\;
    chown -R nginx:nginx ./var/{sessions,data,cache,logs}
    chown -R nginx:nginx ./public/{media,js}

    echo "\n*********************************************************************************"
    echo "************** Step 4: Post-installation Environment Configuration **************"
    echo "*********************************************************************************\n"

    echo "\n~~~~~~~~~~~~~~ Schedule Periodical Command Execution ~~~~~~~~~~~~~~\n"

    echo "*/1 * * * * php /var/www/oroapp/bin/console oro:cron --env=prod > /dev/null" > /var/spool/cron/nginx

    echo "\n~~~~~~~~~~~~~~ Configure and Run Required Background Processes ~~~~~~~~~~~~~~\n"

    cat >> /etc/systemd/system/oro-message-queue.service <<__EOF__
[Unit]
Description=ORO consumer for /var/www/oroapp
After="postgresql rabbitmq-server redis elasticsearch"

[Service]
Type=simple
User=nginx
WorkingDirectory=/var/www/oroapp
ExecStart=/usr/bin/php /var/www/oroapp/bin/console oro:message-queue:consume --env=prod --memory-limit=500
Restart=always
RestartSec=3s
TimeoutStopSec=3s
KillMode=control-group
PrivateTmp=true

[Install]
WantedBy=multi-user.target
__EOF__

    cat >> /etc/systemd/system/oro-clank-server.service <<__EOF__
[Unit]
Description=ORO clank server for /var/www/oroapp
After="postgresql rabbitmq-server redis elasticsearch"

[Service]
Type=simple
User=nginx
WorkingDirectory=/var/www/oroapp
ExecStart=/usr/bin/php /var/www/oroapp/bin/console gos:websocket:server --env=prod
Restart=always
RestartSec=3s
KillMode=control-group
PrivateTmp=true

[Install]
WantedBy=multi-user.target
__EOF__

    systemctl enable --now oro-message-queue.service oro-clank-server.service

    echo "\n**********************************************************************************************************************"
    echo "************** Congratulations! You’ve Successfully Installed OroCommerce Application **********************************"
    echo "***********************************************************************************************************************\n"
    echo "\n************** You should now be able to open the homepage http://$APP_HOST:$FORWARDED_PORT/ and use the application. ************\n"
   SHELL
end

